Buoi4_1/Buoi4_1/Models/NhanVien.cs
using System.ComponentModel.DataAnnotations;

namespace Buoi4_1.Models
{
    public class NhanVien
    {
        [Required]
        [Display(Name = "Mã Nhân Viên")]
        public int MaNV { get; set; }
        [Required]
        [Display(Name = "Họ và Tên")]
        public string HoTen { get; set; }
        [Required]
        [Display(Name = "Ngày Sinh")]
        public NgaySinh a { get; set; }
        [Required]
        [Display(Name = "Giới Tính")]
        public string GioiTinh { get; set; }
        [Required]
        [Display(Name = "Số Điện Thoại")]
        public int SoDT { get; set; }
        [Required]
        [Display(Name = "Hệ Số Lương")]
        public decimal HSLuong { get; set; }
        [Required]
        [Display(Name = "Lương")]
        public float Luong { get; set; }
        [Required]
        [Display(Name = "Tên Phòng")]
        public string TenPhong { get; set; }
    }
    
}

Buoi4_1/Buoi4_1/Controllers/NhanVienController.cs
using Buoi4_1.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging;
using System.Collections;

namespace Buoi4_1.Controllers
{
    public class NhanVienController : Controller
    {
        static public List<NhanVien> a = new List<NhanVien>
        {
            new NhanVien
            {
                MaNV = 1,
                HoTen = "Việt Anh",
                a = new NgaySinh {Ngay = 25, Thang = 6, Nam = 2004},
                GioiTinh = "Nam",
                SoDT = 0971975053,
                HSLuong = 4.33m,
                Luong = 1084235,
                TenPhong = "IT"
            },
            new NhanVien
            {
                MaNV = 2,
                HoTen = "Em Xinh",
                a = new NgaySinh {Ngay = 6, Thang = 4, Nam = 1995},
                GioiTinh = "Nữ",
                SoDT = 0974456424,
                HSLuong = 6.78m,
                Luong = 8022378,
                TenPhong = "IT"
            },
            new NhanVien
            {
                MaNV = 3,
                HoTen = "Nguyen Van C",
                a = new NgaySinh {Ngay = 1, Thang = 4, Nam = 2014},
                GioiTinh = "Nam",
                SoDT = 0945456424,
                HSLuong = 3.98m,
                Luong = 1234538,
                TenPhong = "Văn Phòng"
            },
            new NhanVien
            {
                MaNV = 4,
                HoTen = "Nguyen Thị D",
                a = new NgaySinh {Ngay = 23, Thang = 11, Nam = 1995},
                GioiTinh = "Nam",
                SoDT = 0954456424,
                HSLuong = 10.12m,
                Luong = 12344338,
                TenPhong = "Văn Phòng"
            },
            new NhanVien
            {
                MaNV = 5,
                HoTen = "Trần Văn E",
                a = new NgaySinh {Ngay = 23, Thang = 5, Nam = 2011},
                GioiTinh = "Nam",
                SoDT = 0951254424,
                HSLuong = 8.74m,
                Luong = 1231238,
                TenPhong = "IT"
            },
        };
        // Tìm kiếm và hiển thị nhân viên có giới tính nữ
        public IActionResult TimKiem1()
        {
            return View(a);
        }

        // Tính tổng lương của các nhân viên của 1 phòng với tên phòng nhập vào textbox
        public IActionResult Tong2()
        {
            return View();
        }
        public IActionResult Tong2_1(string s)
        {
            var NV = new List<NhanVien>();
            foreach(NhanVien temp in a)
            {
                if(temp.TenPhong == s) 
                    NV.Add(temp);
            }
            if(NV.Any())
            {
                float TongLuong = NV.Sum(m => m.Luong);
                ViewBag.Tong = TongLuong;   
                ViewBag.s = s;
                return View();
            }
            else
            {
                ViewBag.ErrorMessage = "Phòng ban không tồn tại. Vui lòng nhập lại.";
                return View("Tong2");
            }    
        }

        //  Tìm kiếm và hiển thị nhân viên của một 1 phòng với tên phòng nhập vào textbox
        public IActionResult Timkiem3()
        {
            return View();
        }
        public IActionResult Timkiem3_1(string s)
        {
            var NV = new List<NhanVien>();
            foreach (NhanVien temp in a)
            {
                if (temp.TenPhong == s)
                    NV.Add(temp);
            }
            if (NV.Any())
            {
                ViewBag.s = s;
                return View(NV);
            }
            else
            {
                ViewBag.ErrorMessage = "Phòng ban không tồn tại. Vui lòng nhập lại.";
                return View("Tong2");
            }
        }

        // GET: NhanVienController
        public ActionResult Index()
        {
            return View(a);
        }

        // GET: NhanVienController/Details/5
        public ActionResult Details(int id)
        {
            NhanVien NV = a.FirstOrDefault(m => m.MaNV == id);
            if(NV == null)
            {
                return NotFound();
            }    
            return View(NV);
        }

        // GET: NhanVienController/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: NhanVienController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NhanVien CreateNV)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CreateNV.MaNV = a.Max(x => x.MaNV) + 1;
                    a.Add(CreateNV);
                    return RedirectToAction("Index");
                }
                return View(CreateNV);
            }
            catch
            {
                return View();
            }
        }
        // GET: NhanVienController/Edit/5
        public ActionResult Edit(int id)
        {
            NhanVien NVEdit = a.FirstOrDefault(u => u.MaNV == id);
            if (NVEdit == null)
            {
                return NotFound();
            }    
            return View(NVEdit);
        }

        // POST: NhanVienController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, NhanVien b)
        {
            try
            {
                NhanVien EditNV = a.FirstOrDefault(u =>u.MaNV == id);
                if(EditNV == null)
                {
                    return NotFound();
                }
                else
                {
                    EditNV.HoTen = b.HoTen;
                    EditNV.a = b.a;
                    EditNV.GioiTinh = b.GioiTinh;
                    EditNV.SoDT = b.SoDT;
                    EditNV.HSLuong = b.HSLuong;
                    EditNV.Luong = b.Luong;
                    EditNV.TenPhong = b.TenPhong;
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: NhanVienController/Delete/5
        public ActionResult Delete(int id)
        {
            NhanVien DeleteNV = a.FirstOrDefault(v => v.MaNV == id);
            if(DeleteNV == null)
            {
                return NotFound();
            }    
            return View(DeleteNV);
        }

        // POST: NhanVienController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, NhanVien NV)
        {
            NhanVien DeleteNV = a.FirstOrDefault(v => v.MaNV == id);
            try
            {
                if (DeleteNV == null)
                {
                    return NotFound();
                }
                else
                {
                    a.Remove(DeleteNV);
                    return RedirectToAction(nameof(Index));
                }    
                
            }
            catch
            {
                return View(DeleteNV);
            }
        }
    }
}

Buoi4_1/Buoi4_1/Views/NhanVien/Create.cshtml
@model Buoi4_1.Models.NhanVien

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>NhanVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HoTen" class="control-label"></label>
                <input asp-for="HoTen" class="form-control" />
                <span asp-validation-for="HoTen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Ngày Sinh</label>
                <div class="row">
                    <div class="col">
                        <input asp-for="a.Ngay" class="form-control" placeholder="Ngày" />
                        <span asp-validation-for="a.Ngay" class="text-danger"></span>
                    </div>
                    <div class="col">
                        <input asp-for="a.Thang" class="form-control" placeholder="Tháng" />
                        <span asp-validation-for="a.Thang" class="text-danger"></span>
                    </div>
                    <div class="col">
                        <input asp-for="a.Nam" class="form-control" placeholder="Năm" />
                        <span asp-validation-for="a.Nam" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDT" class="control-label"></label>
                <input asp-for="SoDT" class="form-control" />
                <span asp-validation-for="SoDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HSLuong" class="control-label"></label>
                <input asp-for="HSLuong" class="form-control" type="number" step="0.01" />
                <span asp-validation-for="HSLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Luong" class="control-label"></label>
                <input asp-for="Luong" class="form-control" />
                <span asp-validation-for="Luong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenPhong" class="control-label"></label>
                <input asp-for="TenPhong" class="form-control" />
                <span asp-validation-for="TenPhong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Buoi4_1/Buoi4_1/Views/NhanVien/Delete.cshtml
@model Buoi4_1.Models.NhanVien

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaNV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaNV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoTen)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.a)
        </dt>
        <dd class="col-sm-10">
            @($"{Model.a.Ngay}/{Model.a.Thang}/{Model.a.Nam}")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoDT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoDT)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HSLuong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HSLuong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Luong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Luong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenPhong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenPhong)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Buoi4_1/Buoi4_1/Views/NhanVien/Details.cshtml
@model Buoi4_1.Models.NhanVien

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaNV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaNV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoTen)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.a)
        </dt>
        <dd class="col-sm-10">
            @($"{Model.a.Ngay}/{Model.a.Thang}/{Model.a.Nam}")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoDT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoDT)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HSLuong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HSLuong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Luong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Luong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenPhong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenPhong)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { Id = Model.MaNV }) |
    <a asp-action="Index">Back to List</a>
</div>

Buoi4_1/Buoi4_1/Views/NhanVien/Edit.cshtml
@model Buoi4_1.Models.NhanVien

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>NhanVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaNV" class="control-label"></label>
                <input asp-for="MaNV" class="form-control" />
                <span asp-validation-for="MaNV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Ngày Sinh</label>
                <div class="row">
                    <div class="col">
                        <input asp-for="a.Ngay" class="form-control" placeholder="Ngày" />
                        <span asp-validation-for="a.Ngay" class="text-danger"></span>
                    </div>
                    <div class="col">
                        <input asp-for="a.Thang" class="form-control" placeholder="Tháng" />
                        <span asp-validation-for="a.Thang" class="text-danger"></span>
                    </div>
                    <div class="col">
                        <input asp-for="a.Nam" class="form-control" placeholder="Năm" />
                        <span asp-validation-for="a.Nam" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="HoTen" class="control-label"></label>
                <input asp-for="HoTen" class="form-control" />
                <span asp-validation-for="HoTen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDT" class="control-label"></label>
                <input asp-for="SoDT" class="form-control" />
                <span asp-validation-for="SoDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HSLuong" class="control-label"></label>
                <input asp-for="HSLuong" class="form-control" type="number" step="0.01" />
                <span asp-validation-for="HSLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Luong" class="control-label"></label>
                <input asp-for="Luong" class="form-control" />
                <span asp-validation-for="Luong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenPhong" class="control-label"></label>
                <input asp-for="TenPhong" class="form-control" />
                <span asp-validation-for="TenPhong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Buoi4_1/Buoi4_1/Views/NhanVien/Index.cshtml
@model IEnumerable<Buoi4_1.Models.NhanVien>

@{
    ViewData["Title"] = "Index";
}

<h1>Danh sách nhân viên</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaNV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoTen)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.a)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HSLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Luong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenPhong)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaNV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)
            </td>
            <td>
                @($"{item.a.Ngay}/{item.a.Thang}/{item.a.Nam}")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @("0" + item.SoDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HSLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Luong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenPhong)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.MaNV }) |
                @Html.ActionLink("Details", "Details", new { id = item.MaNV }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MaNV })
            </td>
        </tr>
}
    </tbody>
</table>

Buoi4_1/Buoi4_1/Views/NhanVien/TimKiem1.cshtml
@model IEnumerable<Buoi4_1.Models.NhanVien>

@{
    ViewData["Title"] = "Index";
}

<h1>Danh sách nhân viên nữ</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaNV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoTen)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.a)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HSLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Luong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenPhong)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if(item.GioiTinh == "Nữ")
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaNV)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HoTen)
                    </td>
                    <td>
                        @($"{item.a.Ngay}/{item.a.Thang}/{item.a.Nam}")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GioiTinh)
                    </td>
                    <td>
                        @("0" + item.SoDT)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HSLuong)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Luong)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenPhong)
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Buoi4_1/Buoi4_1/Views/NhanVien/Timkiem3.cshtml
<h1>Thông tin nhân viên của 1 phòng ban</h1>

@{
    Html.BeginForm("Timkiem3_1", "NhanVien", FormMethod.Post);
    {
        @Html.Label("Nhập tên phòng ban cần tìm kiếm")
        <br />
        @Html.TextBox("s")
        <br />
        <input type="submit" value="Tìm kiếm" />
    }
}
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger mt-3">
        @ViewBag.ErrorMessage
    </div>
}

Buoi4_1/Buoi4_1/Views/NhanVien/Timkiem3_1.cshtml
@model IEnumerable<Buoi4_1.Models.NhanVien>
<h1>Danh sách nhân viên của phòng ban @ViewBag.s</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaNV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoTen)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.a)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HSLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Luong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenPhong)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoTen)
                </td>
                <td>
                    @($"{item.a.Ngay}/{item.a.Thang}/{item.a.Nam}")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GioiTinh)
                </td>
                <td>
                    @("0" + item.SoDT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HSLuong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Luong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenPhong)
                </td>
            </tr>
        }
    </tbody>
</table>

Buoi4_1/Buoi4_1/Views/NhanVien/Tong2.cshtml
<h1>Tổng lương của 1 phòng ban</h1>

@{
    Html.BeginForm("Tong2_1", "NhanVien", FormMethod.Post);
    {
        @Html.Label("Nhập tên phòng ban cần tính lương")
        <br />
        @Html.TextBox("s")
        <br />
        <input type="submit" value="Tổng lương" />
    }
}
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger mt-3">
        @ViewBag.ErrorMessage
    </div>
}

Buoi4_1/Buoi4_1/Views/NhanVien/Tong2_1.cshtml
<h1>Tổng lương của phòng ban @ViewBag.s</h1>
<p>Tổng lương: @ViewBag.Tong</p>